### ISSUE TITLE
Class Diagram Revision

### ISSUE THREAD

**Issue by HarunErgen** [bounswe/bounswe2023group1#116]
With @alperenDagi, we have created the classes, determined their fields, methods, and relationships between them. The parameters of the methods should be written. Also, it should be checked whether the classes represent the structure of the platform properly. We should have a meeting for the class diagram revision.

#91 #95 #100 #110

**Comment by alitpc25** [comment]
Thanks a lot for your efforts on class diagram creation. But, I copied the diagram you drew and edited a bit. Here is the diagram:
https://app.diagrams.net/?src=about#G1J9cNpL46UXp2WWsj89zzaMFlXSSd4RZ2

And here is my views:
*I think we don't need another class called Profile since when a user registers, he provides all of the fields in the Profile class you created. Instead, we can combine them into one class called User and in this class, we should state every fields a User can have and every method a user can use.
*Also, in Admin class, we don't need to keep data of List<BannedUser>, instead we can create a new Enum UserState and add a new field "state" to User class so that we can change user's state easily and manage banned users accordingly.
*Also, all of the class must have id to insert, update etc. with database by that id.
*In addition, I know this class diagram is not complete yet, but we also be careful about fields' access modifiers (+,-). If a field is private for example, it should have getter & setter methods, too.

These are my points for now.

**Comment by alperenDagi** [comment]
@alitpc25  I have evaluated the modifications made to the project, and it appears that the improvements made may not have significantly contributed to the project's advancement or may not have been relevant to meeting the necessary requirements. While I acknowledge the value of enhancing the design, I believe it is essential to prioritize completing the necessary specifications before addressing personal preferences. Focusing on project's objectives effectively is the most important part now.

**Comment by kubraaksux** [comment]
I appreciate your work @alperenDagi @HarunErgen 
Cclass diagram revised by me to ensure that it accurately reflects the structure of the platform and all necessary method parameters and return types added. For the completeness and accuracy I changed some methods, and added some methods I see necessary. Still I think there is more to discuss. Since every person is more dominated at the use cases they created and you have comprehensive look to the class diagrams, new meeting is necessary with you and assignees of use cases.

**Comment by kubraaksux** [comment]
A meeting -meeting 12- #134 scheduled and done to review and discuss the revised diagram to ensure that it is complete and accurate.
Absent relations between classes, absent methods and object types are discussed and updated. With a 3 hours work of 6 people, class diagrams almost finalised. 
@kubraaksux @alperenDagi @alitpc25 @HarunErgen @furknbulbul @cemsarpkaya

**Comment by kubraaksux** [comment]
MISSING

- [ ] and has to be done: Category enum sub titles need to be edited. Every category need a typelist!!

This is assigned to @cemsarpkaya 

After that. Everything will be completed for class diagrams.

**Comment by HarunErgen** [comment]
Completed and revisioned.  
[Class Diagrams](https://github.com/bounswe/bounswe2023group1/wiki/Class-Diagrams)
