### ISSUE TITLE
Review Use Case Diagram

### ISSUE THREAD

**Issue by kubraaksux** [bounswe/bounswe2023group1#242]
### Review Use Case Diagrams
Revisit use case diagrams, check on inconsistencies and fixes.
Consider feedbacks from last semester.
Pursue enhancements.

**Comment by volcaniqueo** [comment]
This is an ongoing issue. Will be continuously reviewed as we implement the backend.

**Comment by kubraaksux** [comment]
UML diagram updates are assigned to the backend team, and mockup reviews are assigned to mobile and web. Since those are better pairings, Requirements specification review task belongs to whole team.

**Comment by furknbulbul** [comment]
I have reviewed the use case diagram and inserted a couple of new blocks since we realized them when backend team discussed the design on backend. We need to distinguish need - request and  task - action couple and changed the use case diagram accordingly. Overall function of roles does not seem to change much.
