### ISSUE TITLE
MVVM Architecture

### ISSUE THREAD

**Issue by kubraaksux** [bounswe/bounswe2023group1#265]

**Comment by alperenDagi** [comment]
As the mobile team, we couldn't begin our work until the designs were finalized. We completed the design phase early, and it has been available to you for a few weeks. If you want us to follow the design you've created, I believe it's important for you to start your work early and communicate this to us. Expecting us to develop applications for demo right before the milestone while also making design changes isn't practical. Let's avoid unnecessary drama and time-wasting. Effective time management, by starting early, can help ensure things progress as desired. Otherwise, we can't be held responsible for last-minute requests.
