### ISSUE TITLE
Confusions with mockups

### ISSUE THREAD

**Issue by kubraaksux** [bounswe/bounswe2023group1#290]
There are confusions and inconsistencies with mockups.

- Did we planned users to have usernames? Because our "sign in" has username part.
- What will be our landing page? Sign in? Sign up? Map without registration? Or choosing the role type? It is not clear and it should be as soon as possible.
- Frontend and mobile team didnt conclude the design choices with the functional ones like the one above.
Those are the issues i have come so far. They needed to be solved and i believe there is more mockup problems that needed to be found and solved then.

**Comment by HarunErgen** [comment]
- "username" should be removed. We won't need or keep such information. While registration, automatic ID assignment could be made on the backend to distinguish users.
- Landing page should be "Sign in" page.

**Comment by kubraaksux** [comment]
I implemented landing page as signup after discussed with some team members especially backend. Then we discussed with frontend team and because of app's urgent help tendency, last implementation was choosing landing page as map. This has to be concluded especially btw front-mobile. 
Also after the customer meeting (milestone presentation) from the feedback of customers i conclude that quick help, quick info of resources can be more preferrable. 
Agreed on username. We also removed it. Also mockups are updated according to that

**Comment by kubraaksux** [comment]
Again, there is still inconsistencies with mobile which should be considered and discussed

**Comment by kubraaksux** [comment]
Not standardized theme also inconsistency btw mobile and front. And i suggest to use ResQ logo with its original color red.

**Comment by kubraaksux** [comment]
- landing page
- color, theme
- at signup web: Already have an account? Sign in -- mobile: Already have an account?  Log in
- at sign in web: Don't have an account? Sign Up--  mobile: Not Registered Yet? Create an account
- at web and sign in "Forgot password?" is under the sign in at mobile it is above the sign in.
- mobile: I accept the terms and privacy policy. web: By signing up, you agree to our Terms , Privacy Policy and Cookies Policy .
- request views and page icons are different
- requests have priority and type at web and mobile. at web additionally they have status.
- user profile significantly different at mobile and web. also web calls it account. 
- my requests, notifications and settings not decided at web yet.
- role shouldnt be selected at log in, mobile should update this. this was a team decision.
-

**Comment by kubraaksux** [comment]
Mobile team decided not to work parallel with the frontend team unfortunately.  I tried my best to find a common way but couldnt make it. 
With all due disrespect to my work i do not want to pursue this and im closing this issue too.
[you can check](https://github.com/bounswe/bounswe2023group1/issues/269)

**Comment by HarunErgen** [comment]
@kubraaksux We can make changes to keep in line on functionality. I have expressed my requests through the WhatsApp platform to the web team for color palettes and similarity in design, but they were not taken into consideration. I guess it was overlooked because I didn't share it on Github. For now we can focus on functionality.

**Comment by alperenDagi** [comment]
As the mobile team, we couldn't begin our work until the designs were finalized. We completed the design phase early, and it has been available to you for a few weeks. If you want us to follow the design you've created, I believe it's important for you to start your work early and communicate this to us. Expecting us to develop applications for demo right before the milestone while also making design changes isn't practical. Let's avoid unnecessary drama and time-wasting. Effective time management, by starting early, can help ensure things progress as desired. Otherwise, we can't be held responsible for last-minute requests.
