### ISSUE TITLE
Web Exit Issue

### ISSUE THREAD

**Issue by kubraaksux** [bounswe/bounswe2023group1#353]
When i clicked to the exit icon, only action happened at the page is replacement of exit icon with sign in and sign up icon. 
If It doesnt functionally work,needs to be resolved. Probably throw to the sign in page.

**Comment by ilgazer** [comment]
@kubraaksux I couldn't exactly understand what you mean with logging out, as website does set the user token to null when you log out. Perhaps you mean that the user could find it hard to understand that they are logged out. In that case, we could redirect them to the main page when they log out, to make it more clear.

If I guessed wrong, could you share some screenshots etc as to what the issue is?

**Comment by kubraaksux** [comment]
Sorry my oversight, i didnt check it properly. Then it is just a navigation problem.

**Comment by kubraaksux** [comment]
solved [check](https://github.com/bounswe/bounswe2023group1/pull/399)
