### ISSUE TITLE
Login problem

### ISSUE THREAD

**Issue by kubraaksux** [bounswe/bounswe2023group1#354]
When i try to sign up with pre-registered email, app allows. But when i try to login then gives error. Can backend check this?

**Comment by alitpc25** [comment]
Backend doesn't allow, we first check if the email already in use. If it is, we return Bad Request with a message "Email is already in use.". The problem is on frontend. Frontend should check what is returned from backend and act accordingly. However, the frontend is always saying "Approved" even we send "Bad request" response. I tried with Swagger and result is below:

![image](https://github.com/bounswe/bounswe2023group1/assets/42305974/7e29c1bb-c21e-4c68-b9f9-0b2203529899)

**Comment by alitpc25** [comment]
Check the problem on frontend and close the issue, please

**Comment by kubraaksux** [comment]
Thanks. We are on it!

**Comment by alitpc25** [comment]
Also, I can login to my account with Swagger API but on the application frontend, i cannot. It says "Signin failed. Please check your credentials."

**Comment by kubraaksux** [comment]
I had the same problem, we will solve it asap

**Comment by kubraaksux** [comment]
solved [check](https://github.com/bounswe/bounswe2023group1/pull/399)

**Comment by kubraaksux** [comment]
solved [check](https://github.com/bounswe/bounswe2023group1/pull/399)
