### ISSUE TITLE
Frontend Implement List View and Filtering to Map Page

### ISSUE THREAD

**Issue by ilgazer** [bounswe/bounswe2023group1#373]
Implement filtering and the sidebar list to the map as per requirements.

**Comment by kubraaksux** [comment]
description of this issue seems wrong. sidebar list is defined as data table in my issue. [378](https://github.com/bounswe/bounswe2023group1/issues/378) and im working on it for a while. "Implement filtering and the sidebar list to the map as per requirements" is the description of my task. 
you can check what i have done at the pr [#385 ](https://github.com/bounswe/bounswe2023group1/pull/385), and at the issue [378](https://github.com/bounswe/bounswe2023group1/issues/378).

to clarify, i'll use images from figma.

<img width="811" alt="Screenshot 2023-11-14 at 02 22 54" src="https://github.com/bounswe/bounswe2023group1/assets/67320250/fabe0b40-2272-401d-a4ee-6c66ae6cf7ff">

left data table with its functionalities is mine. 

right search with its functionalities is yours.

<img width="831" alt="Screenshot 2023-11-14 at 02 23 27" src="https://github.com/bounswe/bounswe2023group1/assets/67320250/3ede5ab1-ec05-4adf-b99a-c6a288e5f390">

**Comment by ilgazer** [comment]
Ok, I was just asking because this was the issue we created during last week's planning. I guess we can close this one and continue the work over at #378

**Comment by kubraaksux** [comment]
Yeah, I know. I created 378 at the lab too. We talked about this. but searching on a map seems like an extra layer to the complexity. When the search on the map is clicked, we can allow the map data table to be opened directly. So that user can make the search there. But we need resources to be seen on the map and at last lab we said that "it can be similar to Sahibinden.com for the sake of visual appeal of map. so all resources and and requests wont be shown on the map. they can conditionally shown".
here we have two options:

1. like Sahibinden, show when user got closer
2. show according to the search criteria at the data table. 

So, what can and should we do about these?

**Comment by ilgazer** [comment]
I must not have been there when the search was discussed. Referencing the requirements, we should create filters based on different factors. In my head, both the map and the list should always be visible, and selecting from one should highlight it in another. What would the search functionality do as distinct from the filters?

**Comment by kubraaksux** [comment]
This is talked about at the lab, so I assumed you knew. But I remember that when we were separating tasks, I stated that I would create a data table for the map with the functionalities, and you decided to take the search functionality for the map.
Since we changed the means of search and filtering to be done in the data table, you can redefine your task as "doing the map visualization part of filtering. and showing results with stacking."

requirements in the scope of this issue:
> 1.1.2.1.3. Victims shall be able to view assistance locations on a map and as a list. (Help centers, soup kitchens, etc.)
> 1.1.2.1.4. Victims shall be able to filter the assistance locations by type and distance.
> 1.1.2.1.5. Victims shall be able to view available resources on a map and as a list.
> 1.1.2.1.6. Victims shall be able to filter resources by name, category, and distance.
> 1.2.7.1. The platform shall have a map interface that displays the appropriate subset of resources, requests, and tasks, along with warnings related to the current situation.
> 1.2.7.2. The map shall be capable of filtering items by the applicable subset of name, category, amount, distance, urgency, and status.
The map data table meets these requirements.

mentioning your previous comment on this issue:
"we should create filters based on different factors. " So, this is done. You can check out my work. mentioned above.
"Both the map and the list should always be visible." This is not discussed. table will be easily accessible by clicking the search button. I think it is more conventional.
"Selecting from one should highlight it in another." Selecting from the map opens the card, and selecting from the table highlights the map location.

I implemented it according to those and what I had stated in the lab. Further can be discussed at tomorrow's lab.
For 373 and search, it is not'search' in general terms; it is a filtering mechanism. I implemented it to make it on the data table, but also a map visual should be done.

As stated above, the "search button will open the data table. Search will actually be a filtering mechanism. Still, part of this is not implemented and should be implemented.
so all resources and requests won't be shown on the map. They can be conditionally shown".
Here we have two options:
like Sahibinden, show when user got closer
show according to the search criteria in the data table."
