### ISSUE TITLE
Implement Card View and Filtering for Map

### ISSUE THREAD

**Issue by ilgazer** [bounswe/bounswe2023group1#414]
As per requirements and discussion with the customer, a list view with cards that correspond to all the points on the map will be implemented. Furthermore, filtering with various categories will be implemented. This will lay the groundwork for covering the following requirements:

1.1.2.1.5. Victims shall be able to view available resources on a map and as a list.
1.1.2.1.6. Victims shall be able to filter resources by name, category and distance.
1.1.2.2.10. Responders shall be able to view all actions in a task assigned to them as a list and on a map.
1.1.2.3.4. Facilitators shall be able to view requests on a map and as a list.
1.1.2.1.5. Facilitators shall be able to filter requests by name, category and distance.
1.1.2.1.6. Coordinators shall be able to view resources, requests and tasks as a list and on a map.
1.1.2.1.7. Coordinators shall be able to filter resources, requests and tasks by whichever subset of name, category, amount, distance, urgency and status is applicable.

**Comment by kubraaksux** [comment]
Those requirements are implemented in my PR [385](https://github.com/bounswe/bounswe2023group1/pull/385),  stated in issues [378](https://github.com/bounswe/bounswe2023group1/issues/378), [418](https://github.com/bounswe/bounswe2023group1/issues/418)
1.1.2.1.5. Victims shall be able to view available resources on a map and as a list.
1.1.2.1.6. Victims shall be able to filter resources by name, category, and distance.

and those can also be implemented with the same data table component:
1.1.2.2.10. Responders shall be able to view all actions in a task assigned to them as a list and on a map.
1.1.2.3.4. Facilitators shall be able to view requests on a map and as a list.
1.1.2.1.5. Facilitators shall be able to filter requests by name, category, and distance.
1.1.2.1.6. Coordinators shall be able to view resources, requests, and tasks as a list and on a map.
1.1.2.1.7. Coordinators shall be able to filter resources, requests, and tasks by whichever subset of name, category, amount, distance, urgency, and status is applicable.

The comprehensive filtering mechanism I have implemented with the data table allows the filtering mechanism to meet all these requirements, such as "filter resources by name, category, and distance" ,  "filter requests by name, category, and distance," and "filter resources, requests, and tasks by whichever subset of name, category, amount, distance, urgency, and status is applicable." . 
The necessary and lacking functionality here is that when an item (request, resource, or action) chosen from the data table, it should be navigated and pointed at the map, and vice versa. If an item is selected from the map, then it should open its details as a request card component, as we implemented.

Those requirements highlight the functionalities of view and filter. Those are provided with a data table component designed for the victim. And only changing column names will be sufficient for other roles.

Moreover, the data table component allows users very advanced filtering mechanisms, the selection option to see all columns or preferred ones, and export opportunities.
We have discussed that this export is especially beneficial for coordinators since they may need reporting, and this export will substitute a report. Also, they can be beneficial for facilitators since, in the disaster area, an export in paper format instead of digital ones can be crucial.
The open discussion was about whether we should keep this data table in use for victims or not. Since we have discussed maybe "Google Maps" view can be great idea too. And lastly, we have not concluded this discussion. 

I think since we have a data table -list- component now and ready to use, we should first focus on map view as mentioned above for better time efficiency and moreover, we should discuss data-table / Google-map style / or hybrid listing.

**Comment by kubraaksux** [comment]
<img width="496" alt="Screenshot 2023-11-23 at 16 31 35" src="https://github.com/bounswe/bounswe2023group1/assets/67320250/7aff341e-67b5-4029-a7aa-7904e68b3a6d">

**Comment by ilgazer** [comment]
The confusion is now resolved. We have decided to use the data table above for the coordinator and facilitator as described in issue #. For the victim, since they will be seeing assistance locations which have lots of detail, the card view makes more sense. This is similarly true for responders, whose main interaction with the map will be viewing the details of tasks.

**Comment by ilgazer** [comment]
Resolved in #461
