### ISSUE TITLE
Responder Mockup Task View Revision

### ISSUE THREAD

**Issue by ilgazer** [bounswe/bounswe2023group1#98]
Currently, the responder mockup has the information of all the tasks in one list, and then there is the checklist for each component of each subtask. Instead, we should have the interface separated out into different subtasks.

By creating different sections for subtasks, we would have the responders more easily see what needs to be done next. They could therefore focus on completing the next tasks and more easily report problems. This approach can also help the responder with the cognitive load of doing a task containing a large number of subtasks.

What do you think?

**Comment by GulbeycanCagri** [comment]
I think it's a good idea, but I'm closer to the checklist version due to the reasons listed below.
1- I think checklists are easy to control. I think we should consider the fact that there might be thousands or even millions of subtasks after a disaster. I think controlling the checklist of a task is faster than controlling tasks with many subtasks.
2- I think checklists are easier to use in our situation. I believe that creating one assignment and one checklist would be easier than creating a task and ten subtasks. Therefore I think subtasks would make the work of users more overwhelming.
3- I think checklists are more popular. Let us admit that people see and use checklists more often than subtasks. Checklists are used in many forms such as shopping lists, inspection forms, shipping information forms, etc. Therefore, I think that users would be more familiar with checking lists than subtasks. Besides, I think it will be more difficult to explain the concept of a subtask to people who are not very determined to learn the features of an application.
4- I think this proposal will cause a workload that won't take us very far. Updating our requirements and mock-ups in order to reach the same goal does not sound like a good idea when we still have a lot of work to do. Furthermore, I think implementing the checklist version would be easier than implementing the subtask version which reduces the potential errors in the future.


Despite everything I wrote, there may be points that I missed. For this reason, I think that people who strongly believe in this idea can make a presentation to the group with new requirements and mock-ups if they want. We may not have understood what you were thinking correctly. Thanks again for the suggestion.

**Comment by HarunErgen** [comment]
Agreed on checklist
